// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Customer
{
    private Customer() 
    {
        Orders = new List<Order>();
    }

    public Customer(string name) : this()
    {
        Name = name;
    }

    public Order CreateOrder(/*int customerId,*/ string address, List<ProductOrder> productOrders)
    {
        Order newOrder = new Order(/*customerId,*/ address, productOrders);
        Orders.Add(newOrder); //Ids are handled here by entity framework
        return newOrder;
    }

    public int CustomerId { get; private set; }

    public string Name { get; private set; }

    public virtual ICollection<Order> Orders { get; private set; }
}