// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Customers
{
    private Customers() { }

    public Customers(string name)
    {
        Name = name;
    }

    public Orders CreateOrder(int customerId, string address, List<ProductOrders> productOrders)
    {
        Orders newOrder = new Orders(customerId, address, productOrders);
        Orders.Add(newOrder);
        return newOrder;
    }

    public int CustomerId { get; private set; }

    public string Name { get; private set; }

    public virtual ICollection<Orders> Orders { get; private set; } = new List<Orders>();
}