// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Orders
{
    private Orders() { }

    public Orders(int customerId, string address, List<ProductOrders> productOrders)
    {
        Date = DateTime.Now;
        CustomerId = customerId;
        Address = address;
        foreach (var productOrder in productOrders)
        {
            ProductOrders.Add(productOrder);
        }
    }

    public int OrderId { get; private set; }

    public DateTime? Date { get; private set; }

    public int? CustomerId { get; private set; }

    public string Address { get; private set; }

    public virtual Customers Customer { get; private set; }

    public virtual ICollection<Deliveries> Deliveries { get; private set; } = new List<Deliveries>();

    public virtual ICollection<ProductOrders> ProductOrders { get; private set; } = new List<ProductOrders>();
}