// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Products
{
    private Products() { }

    public int ProductId { get; private set; }

    public string Name { get; private set; }

    public decimal? Price { get; private set; }

    public virtual ICollection<ProductOrders> ProductOrders { get; private set; } = new List<ProductOrders>();
}