// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class ProductOrder
{
    private ProductOrder() { }

    public ProductOrder(int productId, decimal price, int quantity) : this()
    {
        ProductId = productId;
        Price = price;
        Quantity = quantity;
    }

    public int OrderId { get; private set; }

    public int ProductId { get; private set; }

    public decimal Price { get; private set; }

    public int Quantity { get; private set; }

    public virtual Order Order { get; private set; }

    public virtual Product Product { get; private set; }
}