// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Domain;
using DataAccess.Mapping;

namespace DataAccess;

public partial class ECommerceCompanyContext : DbContext
{
    public ECommerceCompanyContext()
    {
    }

    public ECommerceCompanyContext(DbContextOptions<ECommerceCompanyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<Deliveries> Deliveries { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<ProductOrders> ProductOrders { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfiguration(new CustomersMap());
        modelBuilder.ApplyConfiguration(new DeliveriesMap());
        modelBuilder.ApplyConfiguration(new OrdersMap());
        modelBuilder.ApplyConfiguration(new ProductOrdersMap());
        modelBuilder.ApplyConfiguration(new ProductsMap());
    }
}